# Generated by Django 4.2.1 on 2023-05-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
    ]
