# Generated by Django 4.2.1 on 2023-05-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_options_alter_menu_options'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE restaurant_menu ORDER BY name ASC;'),
    ]
